#!/usr/bin/python

import Adafruit_DHT
import time

sensor = Adafruit_DHT.DHT22

# connected to GPIO2.
pin = 2

# Try to grab a sensor reading.  Use the read_retry method which will retry up
# to 15 times to get a sensor reading (waiting 2 seconds between each retry).
humidity, temperature = Adafruit_DHT.read_retry(sensor, pin)

# Note that sometimes you won't get a reading and
# the results will be null (because Linux can't
# guarantee the timing of calls to read the sensor).
# If this happens try again!

while True:
    if humidity is not None and temperature is not None:
        print('{0:0.1f} {1:0.1f}'.format(temperature, humidity))
    else:
        print('- -'.format(temperature, humidity))
    time.sleep(1)
