#!/bin/sh

NAL_SEPARATOR=00000001
fifo-broadcaster -i $PIPES_DIR/$VIDEO_RECORDING_PIPE --ws-port=$VIDEO_STREAMER_WS_PORT --tcp-port=$VIDEO_STREAMER_TCP_PORT --chunk-separator=$NAL_SEPARATOR --keep-separator=beginning-of-next
