#!/bin/sh

/opt/vc/bin/raspivid --nopreview --width $VIDEO_WIDTH --height $VIDEO_HEIGHT --framerate $VIDEO_FRAMERATE --profile baseline --timeout 0 --inline -ih -rot $VIDEO_ROTATION -br $VIDEO_BRIGHTNESS -v -o $PIPES_DIR/$VIDEO_RECORDING_PIPE
