version: '3'
services:
  baby-monitor:
    build: .
    privileged: true
    network_mode: "host"
    devices:
      - "/dev/vchiq:/dev/vchiq"
    volumes:
      - /dev/snd/pcmC0D0p:/dev/snd/pcmC0D0p
      - /dev/snd/pcmC1D0c:/dev/snd/pcmC1D0c
      - /dev/snd/controlC0:/dev/snd/controlC0
      - /dev/snd/controlC1:/dev/snd/controlC1
      - /opt/vc/lib:/opt/vc/lib
    ports:
      - 8888:8888
      - 8081:8081
    command: "/bin/sh"
