#!/usr/bin/python

import Adafruit_DHT
import time
import sys

sensor = Adafruit_DHT.DHT22

# connected to GPIO2.
pin = 2

while True:
    humidity, temperature = Adafruit_DHT.read_retry(sensor, pin)
    if humidity is not None and temperature is not None:
        sys.stdout.write('{0:0.1f} {1:0.1f}\n'.format(temperature, humidity))
    else:
        sys.stdout.write('- -'.format(temperature, humidity))

    sys.stdout.flush()
    time.sleep(1)
