#!/bin/sh

fifo-broadcaster -i $PIPES_DIR/$RAW_VIDEO_RECORDING_PIPE --ws-port=$RAW_VIDEO_STREAMER_WS_PORT --tcp-port=$RAW_VIDEO_STREAMER_TCP_PORT --buffer-size=$(expr $VIDEO_WIDTH \* $VIDEO_HEIGHT \* 12 \/ 8)
