#!/usr/bin/env node

const Splitter = require('stream-split');

const NALseparator = new Buffer.from([0,0,0,1]);

const liveStream = process.stdin.pipe(new Splitter(NALseparator));

liveStream.on('data', data => {
  process.stdout.write(Buffer.concat([NALseparator, data]));
});

