#!/usr/bin/env node

const WebSocket = require('ws');
const createReadableStreamHandler = require('../lib/read-stream-handler');

const argv = require('optimist')
    .usage('Broadcasts input stream over websockets\nUsage: $0')
    .options('i', {
      alias : 'input',
      describe: 'Input file',
      demand: true,
    })
    .options('p', {
      alias : 'port',
      describe: 'server port',
      default: 8080,
    })
    .argv;


console.log('initialising');

const source = argv.input;
const port = argv.port;

const wss = new WebSocket.Server({ port });

wss.on('connection', function connection(ws) {
  console.log('client connected');
  ws.on('close', () => console.log('client disconnected'));
});

const onData = (data) => {
  wss.clients.forEach((client) => {
    if(client.readyState !== WebSocket.OPEN){
      return;
    }
    client.send(data);
  });
}

const onClose = () => {
  console.log('reinitialising stream');
}

createReadableStreamHandler({ source, onData, onClose });
